### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by piux2**

### CODE REVIEW

**Comment by moul** [comment]
Hey @piux2, 

What's the current state of this tutorial; do you plan to improve it soon?

Before merging, please update the PR to follow the style with punctuation and resolve the conflict, thank you.

**Comment by zivkovicmilos** [comment]
@piux2 @moul
Is this PR still active?

**Comment by moul** [comment]
Dunno. @piux2 ?

**Comment by waymobetta** [comment]
@piux2 Is there an update on this PR?

**Pull request closed without merging**
